IVoice.Web/Models/Forum/Create.cs
using IVoice.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IVoice.Models.Forum
{
    public class Create : BaseModel, ICrudModel<Database.Category>
    {
        public string AreaName { get; set; }
        public string Description { get; set; }


        public bool IsValid()
        {
            if (string.IsNullOrEmpty(AreaName))
                return false;
            else if (string.IsNullOrEmpty(Description))
                return false;

            return true;
        }

        public Database.Category ToEntity(int LoggedUserId, object ObjectToCast)
        {
            return new Database.Category()
            {
                Name = AreaName,
                Description = Description,
                OnlyForum = true,
                Active = true,
                DateCreated = DateTime.Now,
                UserIdCreate = LoggedUserId,
                ImagePath = null,
            };
        }
    }
}

IVoice.Web/Models/ForumAnswers/Create.cs
using IVoice.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web.Mvc;

namespace IVoice.Models.ForumAnswers
{
    public class Create : BaseModel, ICrudModel<Database.ForumAnswer>
    {
        public int TopicId { get; set; }
        public string TopicName { get; set; }
        [AllowHtml]
        public string Answer { get; set; }
        public Guid UniqueId { get; set; }


        public bool IsValid()
        {
            if (string.IsNullOrEmpty(Answer))
                return false;

            return true;
        }

        public Database.ForumAnswer ToEntity(int LoggedUserId, object ObjectToCast)
        {
            return new Database.ForumAnswer()
            {
                Active = true,
                Answer = Answer,
                AnswerDate = DateTime.Now,
                UserId = LoggedUserId,
                TopicId = TopicId
            };
        }
    }
}

IVoice.Web/Models/ForumTopic/Create.cs
using System;
using IVoice.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using IVoice.Models.Common;

namespace IVoice.Models.ForumTopic
{
    public class Create : BaseModel, ICrudModel<Database.ForumTopic>
    {
        public int CategoryId { get; set; }
        public string TopicName { get; set; }

        [AllowHtml]
        public string TopicBody { get; set; }
        public object Attachments { get; set; }
        public Guid UniqueId { get; set; }

        public SelectList CategoryList { get; set; }


        public bool IsValid()
        {
            if (string.IsNullOrEmpty(TopicName))
                return false;
            else if (string.IsNullOrEmpty(TopicBody))
                return false;

            return true;
        }

        public Database.ForumTopic ToEntity(int LoggedUserId, object ObjectToCast)
        {
            return new Database.ForumTopic()
            {
                Active = true,
                CategoryId = CategoryId,
                Name = TopicName,
                StartDate = DateTime.Now,
                UserId = LoggedUserId,
                Replies = 0,
                Views = 0,
                LastReplyDate = DateTime.Now,
            };
        }


        public Database.ForumAnswer ToAnswerEntity(int LoggedUserId, int TopicId)
        {
            return new Database.ForumAnswer()
            {
                Active = true,
                Answer = TopicBody,
                TopicId = TopicId,
                UserId = LoggedUserId,
                AnswerDate = DateTime.Now,
            };
        }
    }
}

IVoice.Web/Models/ForumTopic/Index.cs
namespace IVoice.Models.ForumTopic
{
    public class Index : BaseModel
    {
        public string AreaName { get; set; }
        public int AreaId { get; set; }
    }
}

IVoice.Web/Models/ForumTopic/SearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IVoice.Models.ForumTopic
{
    public class SearchModel: BaseModel
    {
        public string SearchText { get; set; }
    }
}

IVoice.Web/Models/ForumTopic/TableRowModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IVoice.Models.ForumTopic
{
    public class TableRowModel
    {
        public string TopicURL { get; set; }
        public string TopicName { get; set; }
        public DateTime TopicDate { get; set; }
        public string Voicer { get; set; }

        public int Replies { get; set; }
        public int Views { get; set; }

        public TableRowModel() { }
    }
}

IVoice.Web/Models/IPSocial/Create.cs
using IVoice.Database;
using IVoice.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IVoice.Models.IPSocial
{
    public class Create : BaseModel, ICrudModel<UsersIP>
    {
        public bool IsValid()
        {
            throw new NotImplementedException();
        }

        public UsersIP ToEntity(int userId, object objectToCast)
        {
            throw new NotImplementedException();
        }
    }
}

IVoice.Web/Models/Whisper/Create.cs
using IVoice.Database;
using IVoice.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IVoice.Models.Whisper
{
    public class Create : BaseModel, ICrudModel<Database.Whisper>
    {
        public Guid _uniqueId { get; set; }
        public string _subject { get; set; }
        [AllowHtml]
        public string _message { get; set; }
        public int _voicerId { get; set; }
        public SelectList _voicers { get; set; }

        public bool IsValid()
        {
            if (_voicerId == 0)
                return false;
            else if (string.IsNullOrEmpty(_subject))
                return false;
            else if (string.IsNullOrEmpty(_message))
                return false;
            return true;
        }

        public Database.Whisper ToEntity(int userId, object objectToCast)
        {
            return new Database.Whisper()
            {
                Body = _message,
                DateSent = DateTime.Now,
                ReadReceiver = false,
                ReadSender = false,
                Title = _subject,
                UserSenderId = userId,
                UserReceiverId = _voicerId
            };
        }
    }
}

IVoice.Web/Controllers/ForumTopicController.cs
using IVoice.Extensions;
using IVoice.Helpers;
using IVoice.Helpers.Extensions;
using IVoice.Helpers.External;
using IVoice.Interfaces;
using IVoice.Models.Common;
using IVoice.Models.ForumTopic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace IVoice.Controllers
{
    [RoutePrefix("forum/topic")]
    public class ForumTopicController : CrudForumController
        <Database.ForumTopic,
         ITopicRepository,
         Create
        >
    {
        protected ICategoryRepository CategoryRepository;
        protected IForumAnswersAttachRepository ForumAnswersAttachRepository;
        protected IForumAnswerRepository ForumAnswerRepository;
        public ForumTopicController(IUserRepository userRepository,
                                    ITopicRepository topicRepository,
                                    ICategoryRepository categoryRepository,
                                    IForumAnswerRepository forumAnswerRepository,
                                    IUserAttachmentsRepository userAttachmentsRepository,
                                    IForumAnswersAttachRepository forumAnswersAttachRepository) : base(userRepository, userAttachmentsRepository, topicRepository)
        {
            CategoryRepository = categoryRepository;
            ForumAnswersAttachRepository = forumAnswersAttachRepository;
            ForumAnswerRepository = forumAnswerRepository;
        }



        [Route("")]
        public ActionResult Index()
        {
            return RedirectPermanent(Url.Action("Index", "Forum"));
        }

        [Route("{id}", Name = "TopicList")]
        public ActionResult Index(int id)
        {
            var element = CategoryRepository.FirstOrDefault(x => x.Id == id);
            if (element == null)
                return Redirect(Url.Action("Index", "Forum"));
            else
            {
                var model = new Index()
                {
                    AreaId = element.Id,
                    AreaName = element.Name
                };
                this.FillBaseModel(model);
                return View(model);
            }
        }

        [HttpGet]
        [Route("create/{id}", Name = "TopicCreate")]
        public ActionResult Create(int id)
        {
            if (id == 0)
                return Redirect(Url.Action("Index", "Forum"));
            var model = new Create
            {
                UniqueId = Guid.NewGuid(),
                CategoryId = id,
                CategoryList = CategoryRepository.LoadAndSelect(x => true, x => new SelectListItem_Custom { Id = x.Id, Description = x.Name }, false).ToSelectList(x => x.Description)
            };
            this.FillBaseModel(model);
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("create/{id}", Name = "TopicCreatePost")]
        public override JsonResult Create(Create model)
        {
            var result = base.Create(model);
            var topicId = (result.Data as Message).Text.ToInt();
            if (topicId > 0)
            {
                var answerId = ForumAnswerRepository.Save(model.ToAnswerEntity(_userID, topicId));

                foreach (var item in ForumAnswersAttachRepository.LoadAndSelect(x => x.UsersAttachment.UserId == _userID &&
                                                                                     x.UsersAttachment.UniqueId == model.UniqueId &&
                                                                                    (x.AnswerId == null || x.AnswerId == 0), x => x, false))
                {
                    item.AnswerId = answerId;
                    ForumAnswersAttachRepository.Save(item);
                }
            }

            return result;
        }


        [HttpPost]
        public JsonResult GetTableList(int AreaId, DataTableParameters dataTableParameters)
        {
            var urlTopic = Url.RouteUrl("AnswerList", new { id = 0 });
            urlTopic = urlTopic.Remove(urlTopic.Length - 1);

            Expression<Func<Database.ForumTopic, bool>> filter = null;
            if (AreaId > 0)
                filter = x => x.Active && x.CategoryId == AreaId;
            else
            {
                var searchText = Session["SearchText"].ToString();
                filter = x => x.Active && (x.Name.Contains(searchText) || x.ForumAnswers.Any(y => y.Active && y.Answer.Contains(searchText)));
            }

            var list = _crudRepository.GetTableRows(dataTableParameters, _crudRepository.GetSorters(dataTableParameters), filter, x => new TableRowModel()
            {
                Replies = x.Replies,
                Views = x.Views,
                Voicer = x.User.Nickname,
                TopicDate = x.StartDate,
                TopicName = x.Name,
                TopicURL = urlTopic + x.Id
            });

            return Json(list, JsonRequestBehavior.AllowGet);
        }


        #region FileUpload
        [HttpPost]
        public override JsonResult FileUpload(int Id, HttpPostedFileBase file, Guid UniqueId)
        {
            var result = base.FileUpload(Id, file, UniqueId);

            var userAttachmentId = Convert.ToInt32(result.Data);
            if (userAttachmentId > 0)
            {
                ForumAnswersAttachRepository.Save(new Database.ForumAnswersAttach
                {
                    UserAttachmentId = userAttachmentId
                });
            }

            return result;
        }


        #endregion

        [Route("search", Name = "TopicListSearch")]
        public ActionResult Search()
        {
            if (Session["SearchText"] == null)
                return RedirectToAction("Index", "Forum");

            var model = new SearchModel()
            {
                SearchText = Session["SearchText"].ToString()
            };
            this.FillBaseModel(model);
            return View(model);
        }
    }
}

IVoice.Web/Views/ForumTopic/Create.cshtml
@using IVoice.Extensions
@model IVoice.Models.ForumTopic.Create
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Forum.cshtml";
}

@section header_scripts{
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=7daytolk6jeltjfjw3x2dy01texvksndtbxn8f9u2j4syqoi"></script>
}

<div class="container">
    <div class="row padding-top-10">
        @using (Ajax.BeginForm("Create", "ForumTopic", new AjaxOptions { OnComplete = "onPostFunction" }, new { id = $"CreateTopic" }))
        {
            @Html.AntiForgeryToken();
            @Html.HiddenFor(m => m.UniqueId);
            <div class="panel with-nav-tabs panel-default">
                <div class="panel-heading">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tabCompose" data-toggle="tab">Start new topic</a></li>
                    </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tabCompose">
                            <div class="form-group col-md-12 col-xs-12 float-left">
                                <label for="area"><span class="req">* </span> Area: </label>
                                @Html.DropDownListAutoCompleteFor(m => m.CategoryId, Model.CategoryList, "", new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-12 col-xs-12 float-left">
                                <label for="subject"><span class="req">* </span> Topic name: </label>
                                @Html.TextBoxFor(m => m.TopicName, new { @class = "form-control", required = "required" })
                            </div>

                            <div class="form-group col-md-12 col-xs-12 float-left">
                                <label for="bodymail"><span class="req">* </span> Body: </label>
                                @Html.TextAreaFor(m => m.TopicBody, new { @class = "form-control", required = "required" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

        @Html.Partial("_UploadFileForum", new IVoice.Models.FileUpload.UploadModel() { UniqueId = Model.UniqueId })

        <div class="form-group col-md-12 padding-bottom-10 text-right">
            <input class="btn btn-success" id="submitForm" type="submit" name="submit_reg" value="Create topic">
        </div>

    </div>
</div>

@section scripts{
    @*<script src="/Scripts/fileupload/js/script.js"></script>*@
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=7daytolk6jeltjfjw3x2dy01texvksndtbxn8f9u2j4syqoi"></script>
    <script>
        var tinyInit = null;
        function redirectToBase() {
            @{
                var urlArea = Url.RouteUrl("TopicList", new { id = 0 });
                urlArea = urlArea.Remove(urlArea.Length - 1);
            }

            window.location.href = '@urlArea' + $("#CategoryId").val();
        }

        function onPostFunction(e) {
            if (e.responseJSON.Text != "FALSE") {
                //apriPopupBootstrap("Topic Created", null, "The topic has been created", {}, true, "Ok", false, "Ok", redirectToBase, redirectToBase, '70%');
                popupBootstrap("Topic Created", null, "The topic has been created", {}, true, "Ok", redirectToBase, false, "", null, '70%', null, false);
            }
            else {
                alertMessage("Error", e.responseJSON.Text);
            }
                //apriPopupBootstrap("Error", null, e.responseJSON.Text, {}, true, "Ok", false, "", null, null, '70%');
        }

        $(document).ready(function () {

            $("#submitForm").on("click", function (e) {
                $("#TopicBody").html(tinyMCE.activeEditor.getContent());

                $("#CreateTopic").submit();
            });

            tinyInit = tinymce.init({
                selector: 'textarea',
                height: 500,
                theme: 'modern',
                plugins: 'print preview searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern help',
                toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat  | fontsizeselect fontselect ',
                image_advtab: true,
                templates: [
                  { title: 'Test template 1', content: 'Test 1' },
                  { title: 'Test template 2', content: 'Test 2' }
                ],
                content_css: [
                  '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                  '//www.tinymce.com/css/codepen.min.css'
                ],
                //themes: "tundora"
                //theme_url: '/Content/custom/skin.min.css'
            });
        });
    </script>
}

IVoice.Web/Views/ForumTopic/Index.cshtml
@model IVoice.Models.ForumTopic.Index
@{
    Layout = "~/Views/Shared/_Forum.cshtml";
}

<div class="row overflow-hidden">
    <!-- content -->
    <div class="content content-layout  ">
        <div class="container">
            <div class="panel with-nav-tabs panel-default margin-top-10">
                <div class="panel-heading">
                    <ul class="nav nav-tabs">
                        <li class="pull-left"><a href="@Url.Action("Index", "Forum")"><i class="fa fa-chevron-circle-left"></i>&nbsp;</a></li>
                        <li class="text-white"><h3>@Model.AreaName</h3></li>
                        <li class="pull-right"><a href="@Url.RouteUrl("TopicCreate", new { id = Model.AreaId })"><i class="fa fa-plus-circle"></i>&nbsp;Start new topic</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <table class="table table-dark table-striped table-hover box-default table-area">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th class="col-md-1"></th>
                            <th class="col-md-1"></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section scripts {
    <script>
        var GetTableListURL = '@Url.Action("GetTableList")';
        var areaIdSearch = @Model.AreaId;
    </script>

    <script src="~/Scripts/views/ForumTopicList.js"></script>

}

IVoice.Web/Views/ForumTopic/Search.cshtml
@model IVoice.Models.ForumTopic.SearchModel
@{
    Layout = "~/Views/Shared/_Forum.cshtml";
}

<div class="row overflow-hidden">
    <!-- content -->
    <div class="content content-layout  ">
        <div class="container">
            <div class="panel with-nav-tabs panel-default margin-top-10">
                <div class="panel-heading">
                    <ul class="nav nav-tabs">
                        <li class="pull-left"><a href="@Url.Action("Index", "Forum")"><i class="fa fa-chevron-circle-left"></i>&nbsp;</a></li>
                        <li class="text-white"><h3>@Model.SearchText</h3></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <table class="table table-dark table-striped table-hover box-default table-area">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th class="col-md-1"></th>
                            <th class="col-md-1"></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section scripts {
    <script>
    var GetTableListURL = '@Url.Action("GetTableList")';
    var areaIdSearch = 0;
    </script>

    <script src="~/Scripts/view/ForumTopicList.js"></script>

}